### ISSUE TITLE
可以试试用机核api减轻服务器压力

### ISSUE THREAD

**Issue by firecloud162** [TOKdawn/gcores-talks-Viewer#1]
感谢你编写的脚本！

我研究过一点儿机核的api接口，供你参考：

用www.gcores.com/gapi/v1/talks/XXXX机博ID 检查机博是否存在。
在返回的json数据里，created-at是创建时间，published-at是审核时间。
我见你的做法是取三个加值，检查是否命中。如果用api的话，你可以考虑按published-at和当时时间的差值来选择加值。

用XMLHttpRequest的POST方法可以为机博和评论点赞。
`var http = new XMLHttpRequest();`
`http.open('POST', 'https://www.gcores.com/gapi/v1/votes', true);`
`http.setRequestHeader('Content-Type', 'application/vnd.api+json');`
`http.send('{"data":{"type":"votes","attributes":{"vote-flag":true},"relationships":{"votable":{"data":{"type":"talks","id":"XXXX机博ID"}},"voter":{"data":{"type":"users","id":"XXXX用户ID"}}}}}');`
如果点赞成功，会返回状态201，同时返回一个json包，包括vote的id。

显示评论可以用
https://www.gcores.com/gapi/v1/talks/XXXX机博ID?include=comments
在返回的json包里找到评论的id以后，可以改一下上面的代码给评论点赞：
`http.send('{"data":{"type":"votes","attributes":{"vote-flag":true},"relationships":{"votable":{"data":{"type":"comments","id":"XXXX评论ID"}},"voter":{"data":{"type":"users","id":"XXXX用户ID"}}}}}');`

**Comment by TOKdawn** [comment]
说实话这个插件基本上就是我一时兴起利用摸鱼时间做的,没花太多的精力去调研,检查ID这个方法现在确实十分简单粗暴,
不过作为一个跑在我Git上的定时脚本,其实没太大的性能影响,每次也就是十几到几十次的http请求而已,而且整点才会从我的服务端出发一次,我也设置了延迟,不会产生太大的压力,没啥太大的优化必要,
作为一个轻量级的油猴脚本我是不太想搞太多跟服务器产生交互的事的,点赞这个操作作为一个非官方插件还是别碰比较好,
评论接口我会看一下,看看能不能做个评论展示出来.
不过据西蒙说机核官方的web机组也已经在做了,我这脚本也就是填补下空窗期罢了.

嘛,还是谢谢你啦,话说你是在哪找到的api接口啊Orz 还有大佬机核用户名是啥啊,我关注下

**Comment by firecloud162** [comment]
我是从chrome的控制台里看到机核的react框架对api调用。
其实我也不是web开发者，只是看到机核的api函数写得特别整齐，很优雅，所以花了些时间研究了一下api和返回的json结构。
这些api都是机核网页调用的，我觉得，虽然官方没公布过api，但也不算是逆向工程，所以我会把我对api的研究发给机核写插件的开发者，尤其是能用api减少对服务器请求的场合:)

**Comment by TOKdawn** [comment]
获取锚点ID的这个东西没啥太大优化的必要,我现在这套二分的逻辑消耗也不算特别大(主要还是懒.
我看了下评论的接口,确实有搞头,找时间抽空吧评论展示写了吧,
之前研究了一下部分图片因为.heic格式没法展示的问题,解决方案是有,
但是感觉一个油猴的脚本引好几个三方js就为了做图片的格式转换多少蠢点,也就没再弄了...

**Comment by firecloud162** [comment]
可能是我没说清楚。我不是说现在的http请求频率对服务器有压力，我是觉得现在整点更新一次的时间间隔太长了:)。
你肯定是已经考虑过请求的发送频次对服务器有压力，才会把更新间隔设成一小时。我想的是：如果你准备缩短竟间隔，又担心给服务器造成压力，可以试试用api，返回的json数据包很小:)

**Comment by firecloud162** [comment]
好，能展示评论就太棒啦！

**Comment by TOKdawn** [comment]
频率再降低我的git commit记录就要爆炸了Orz 反正给用户加载最新的方案了嘛,
我本来规划的下一步优化是做一个记录上一次浏览位置的功能,就是每次看机博默认展示到你上次关闭时候的位置,
然后再给个回到最新的按钮,点击的时候不光回到锚点ID我还会自动给做一次向前10条的检索,基本上也就cover住大部分情况了.

**Comment by firecloud162** [comment]
啊，这样啊，我不懂，不懂技术细节，我以为用户在运行脚本以后，会在本地保存一个锚点，下次运行时去本地缓存里读文件
我先去研究下怎么在chrome里装个油猴……

**Comment by firecloud162** [comment]
油猴已启动。插件NB！
[赞][赞]
